pipeline {
    agent any

    environment {
        MAVEN_HOME = "/usr/local/apache-maven-3.9.9"
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }

    stages {
        stage("Setup Maven") {
            steps {
                sh 'mvn -version'
            }
        }

        stage("Clone Repos") {
            steps {
                sh 'git clone https://github.com/Nileshgithub23/simple-java-maven-app.git'
            }
        }

        stage("Build") {
            steps {
                sh 'cd simple-java-maven-app && mvn clean install'
            }
        }
    }
}
