pipeline {
    agent any

    environment {
        MAVEN_HOME = "/usr/local/apache-maven-3.9.9"
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }

    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }

        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }

        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }

        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
            post {
                always {
                    junit 'simple-java-maven-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage("Deliver") {
            steps {
                sh "sh simple-java-maven-app/jenkins/scripts/deliver.sh"
            }
        }

        stage("Complete") {
            steps {
                echo "Job Complete"
            }
        }
    }
}
